baseurl = "https://daideguchi.github.io/tec_studies_blog/"
title = "人生を変えるプログラミング"
DefaultContentLanguage = "ja"
languageCode = "ja-JP"
paginate = "10" # Number of posts per page
theme = "mainroad"
publishDir = "docs"
googleAnalytics = "UA-XXXXXXXXX-X" # Enable Google Analytics by entering your tracking id

[Author] # Used in authorbox
  name = "Dai"
  bio = "本サイトの管理人です。好きなキャラクターはジャックです。"
  avatar = "./img/profile.PNG"

[Params]
  subtitle = "学習のアプトプット" # Deprecated in favor of .Site.Params.logo.subtitle
  description = "公務員がプログラミングを学び、自立していくストーリー" # Site description. Used in meta description
  copyright = "DD" # Footer copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  schema = true # Enable Schema
  twitter_cards = true # Enable Twitter Cards if true
  readmore = false # Show "Read more" button in list if true
  authorbox = false # Show authorbox at bottom of pages if true
  toc = true # Enable Table of Contents
  pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
  post_meta = ["date", "categories"] # Order of post meta information
  mainSections = ["post"] # Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "2006-01-02" # Change the format of dates
  mathjax = true # Enable MathJax
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  highlightColor = "#009406" # Override highlight color
#   customCSS = ["css/custom.css"] # Include custom CSS files
#   customJS = ["js/custom.js"] # Include custom JS files

[Params.logo]
#  image = "img/aprofile.PNG" # Logo image. Path relative to "static"
  title = "人生を変えるプログラミング" # Logo title, otherwise will use site title
  subtitle = "学習のアプトプット" # Logo subtitle

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "profile", "recent", "categories", "taglist", "social"]
  # alternatively "ddg-search" can be used, to search via DuckDuckGo
  # widgets = ["ddg-search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = true # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
  # Enable parts of social widget
#   facebook = "username"
   twitter = "@dai_fukuoka"
#   instagram = "username"
#   linkedin = "username"
#   telegram = "username"
   github = "daideguchi"
#   gitlab = "username"
#   bitbucket = "username"
#   email = "m.pokemori@gmail.com"

[[Params.widgets.social.custom]]
  title = "個人ブログ"
  url = ""

[[Menus.main]]
  Name = "トップ"
  URL = "/"
  weight = 1

[[Menus.main]]
  Name = "カテゴリー"
  URL = "/categories/"
  weight = 2

[[Menus.main]]
  Name = "タグ"
  URL = "/tags/"
  weight = 3

[[Menus.footer]]
  Name = "プライバシーポリシー"
  URL = "/privacy/"
